# Generated by Django 5.1.6 on 2025-03-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_colour',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
