# Generated by Django 5.1.6 on 2025-03-22 15:55

import accounts.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_avatar_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_colour',
            field=models.CharField(blank=True, default=accounts.helpers.get_random_avatar_colour, max_length=50, null=True),
        ),
    ]
